# -*- coding: utf-8 -*-
"""Machine Learning Project - Iris Flower Classification .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyU8idcsiCEFA5gzXvt_gJO3YQWjk4Iq

# **Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

"""# **Import Dataset**"""

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names=["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
df = pd.read_csv(url, names=column_names)

df.head()

type(df)

df.describe()

sns.pairplot(df, hue='class')
plt.show()

x=df.drop('class', axis=1)
y=df['class']

x

y

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

X_train

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x,y)

y_pred=knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))

print(classification_report(y_test,y_pred))

X_test.head(2)

new_data = pd.DataFrame({
    'sepal_length': [6.7],
    'sepal_width': [3.1],
    'petal_length': [5.6],
    'petal_width': [2.4]
})

print(new_data)

prediction=knn.predict(new_data)

prediction[0]

df.iloc[100:]